blueprints/oauthServer/app.py
import os
from flask import Flask
from APIBase.utils.extensions import db
from .oauth2 import config_oauth
from .routes import oauth


def create_app(config=None):
    app = Flask(__name__)

    # load default configuration
    app.config.from_object('website.settings')

    # load environment configuration
    if 'WEBSITE_CONF' in os.environ:
        app.config.from_envvar('WEBSITE_CONF')

    # load app sepcified configuration
    if config is not None:
        if isinstance(config, dict):
            app.config.update(config)
        elif config.endswith('.py'):
            app.config.from_pyfile(config)

    setup_app(app)
    return app


def setup_app(app):
    db.init_app(app)
    config_oauth(app)
    app.register_blueprint(oauth, url_prefix='')

blueprints/oauthServer/routes.py
from flask import Blueprint, request, session, url_for
from flask import render_template, redirect, jsonify
from werkzeug.security import gen_salt
from authlib.integrations.flask_oauth2 import current_token
from authlib.oauth2.rfc6749 import OAuth2Error
from APIBase.models.models import  User, OAuth2Client
from APIBase.utils.extensions import db
from .oauth2 import authorization, require_oauth
import logging

oauth = Blueprint('oauth',__name__, template_folder='templates',url_prefix='/oauth')

def current_user():
	if 'id' in session:
		uid = session['id']
		return User.query.get (uid)
	return None


@oauth.route ('/', methods=('GET', 'POST'))
def oauth_home():
	if request.method == 'POST':
		username = request.form.get ('username')
		user = User.query.filter_by (username=username).first ()
		if not user:
			user = User (username=username)
			db.session.add (user)
			logging.debug('User Name Created' + str(user))
			db.session.commit ()
		logging.debug('User Id for Session' + str (user.id))
		session['id'] = user.id
		return redirect (url_for('oauth.oauth_home'))
	user = current_user ()
	if user:
		clients = OAuth2Client.query.filter_by (user_id=user.id).all ()
	else:
		clients = []
	return render_template ('oAuthServer/home.html', user=user, clients=clients)


@oauth.route ('/logout')
def oauth_logout():
	del session['id']
	return redirect (url_for('oauth.oauth_home'))


@oauth.route ('/create_client', methods=('GET', 'POST'))
def oauth_create_client():
	user = current_user ()
	if not user:
		return redirect ('/')
	if request.method == 'GET':
		return render_template ('oAuthServer/create_client.html')
	client = OAuth2Client (**request.form.to_dict (flat=True))
	client.user_id = user.id
	client.client_id = gen_salt (24)
	if client.token_endpoint_auth_method == 'none':
		client.client_secret = ''
	else:
		client.client_secret = gen_salt (48)
	db.session.add (client)
	db.session.commit ()
	return redirect (url_for('oauth.oauth_home'))


@oauth.route ('/authorize', methods=['GET', 'POST'])
def oauth_authorize():
	'''
	user = current_user ()
	if request.method == 'GET':
		try:
			grant = authorization.validate_consent_request (end_user=user)
			info = grant.client
			oargs = {'client_id': info.client_id,
					 'response_type': request.values['response_type'],
					 'scope': request.values['scope'],
					 'redirect_uri': request.values['redirect_uri']}
			oclientSec = {'client_secret': info.client_secret}
		except OAuth2Error as error:
			return error.error
		return render_template ('oAuthServer/authorize.html', user=user, grant=grant)
	if not user and 'username' in request.form:
		username = request.form.get ('username')
		user = User.query.filter_by (username=username).first ()
	if request.form['confirm']:
		grant_user = user
	else:
		grant_user = None

	return authorization.create_authorization_response (grant_user=grant_user)
	# form = ReusableForm (request.form, amazonAskID='123')
	# return render_template ('oAuthServer/index2.html', form=form)
	
	'''
	logging.debug('.....Oauth Authorization Funcation...........')
	global oargs
	global oclientSec
	try:
		grant = authorization.validate_consent_request (end_user=None)
	except OAuth2Error as error:
		return error.error
	info = grant.client
	user='changeme'
	
	oargs = {'client_id': info.client_id,
				'response_type': request.values['response_type'],
				'scope': request.values['scope'],
				'redirect_uri': request.values['redirect_uri'],
			    'state': request.values['state']}
	oclientSec = {'client_secret': info.client_secret}
	logging.debug((str(oargs)))
	url = url_for ('tokenLinking.tokenLinking_index', alexaID=user)
	logging.debug(str(url))
	return redirect (url_for ('tokenLinking.tokenLinking_index', alexaID=user))
	

# return alexaAPI_index ('123321')

@oauth.route ('/code/<alexaid>', methods=['GET', 'POST'])
def oauth_code(alexaid):
	logging.debug(str(alexaid))
	user = User.query.filter_by (username=alexaid).first ()
	logging.debug (str (user))
	if not user:
		user = User (username=alexaid)
		db.session.add (user)
		db.session.commit ()
	user = User.query.filter_by (username=alexaid).first ()
	grant = authorization.validate_consent_request (end_user=user)
	return authorization.create_authorization_response (grant_user=user)


@oauth.route ('/token', methods=['POST'])
def oauth_issue_token():
	return authorization.create_token_response ()


@oauth.route ('/revoke', methods=['POST'])
def oauth_revoke_token():
	return authorization.create_endpoint_response ('revocation')


@oauth.route ('/api/me')
@require_oauth ('all')
def oauth_api_me():
	user = current_token.user
	return jsonify (id=user.id, username=user.username)

templates/oAuthServer/authorize.html
<p>{{grant.client.client_name}} is requesting:
<strong>{{ grant.request.scope }}</strong>
</p>

<form action="" method="post">
  <label>
    <input type="checkbox" name="confirm">
    <span>Consent?</span>
  </label>
  {% if not user %}
  <p>You haven't logged in. Log in with:</p>
  <div>
    <input type="text" name="username">
  </div>
  {% endif %}
  <br>
  <button>Submit</button>
</form>

templates/oAuthServer/create_client.html
<style>
  label, label > span { display: block; }
  label { margin: 15px 0; }
</style>

<a href="{{ url_for('oauth.oauth_home') }}">Home</a>

<form action="" method="post">
  <label>
    <span>Client Name</span>
    <input type="text" name="client_name">
  </label>
  <label>
    <span>Client URI</span>
    <input type="url" name="client_uri">
  </label>
  <label>
    <span>Allowed Scope</span>
    <input type="text" name="scope">
  </label>
  <label>
    <span>Redirect URIs</span>
    <textarea name="redirect_uri" cols="30" rows="10"></textarea>
  </label>
  <label>
    <span>Allowed Grant Types</span>
    <textarea name="grant_type" cols="30" rows="10"></textarea>
  </label>
  <label>
    <span>Allowed Response Types</span>
    <textarea name="response_type" cols="30" rows="10"></textarea>
  </label>
  <label>
    <span>Token Endpoint Auth Method</span>
    <select name="token_endpoint_auth_method">
      <option value="client_secret_basic">client_secret_basic</option>
      <option value="client_secret_post">client_secret_post</option>
      <option value="none">none</option>
    </select>
  </label>
  <button>Submit</button>
</form>

templates/oAuthServer/home.html
{% if user %}
<style>pre{white-space:wrap}</style>
<div>Logged in as <strong>{{user}}</strong> (<a href="{{ url_for('oauth.oauth_logout') }}">Log Out</a>)</div>

{% for client in clients %}
<pre>
{{ client.client_info|tojson }}
{{ client.client_metadata|tojson }}
</pre>
<hr>
{% endfor %}

<br><a href="{{ url_for('oauth.oauth_create_client') }}">Create Client</a>

{% else %}
<form action="" method="post">
  <input type="text" name="username" placeholder="username">
  <button type="submit">Login / Signup</button>
</form>
{% endif %}